src/models/user.py
from extentions import db


class User(db.Model):
    __tableName__ = 'users'
    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(80),nullable=False,unique=False)
    email = db.Column(db.String(200),nullable=False,unique=True)
    password = db.Column(db.String(200))
    created_at = db.Column(db.DateTime(),nullable=False,server_default=db.func.now())
    updated_at = db.Column(db.DateTime(),nullable=False,server_default=db.func.now(),onupdate=db.func.now())

    @property
    def data(self):
        return{
            'id':self.id,
            'name':self.name,
            'email':self.email,
            'password':self.password
        }

    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_all(cls):
        r = cls.query.all()
        result=[]

        for i in r:
            result.append(i.data)
        return result
    
    @classmethod
    def get_by_id(cls,id):
        return cls.query.filter(cls.id==id).first()

src/app.py
from flask import Flask,render_template
from config import Config
from extentions import db
from flask_migrate import Migrate
from routes import main


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    register_resources(app)
    register_extentions(app)
    return app

def register_extentions(app):
    db.init_app(app)
    migrate = Migrate(app,db)

def register_resources(app):
    app.register_blueprint(main)    

if __name__ == '__main__':
    app = create_app()
    app.run('127.0.0.1',5000)

src/controllers/user.py
from flask import request
from models.user import User
from extentions import db

def add_user_function():
    if request.method == "POST":
        name=request.form["name"]
        email=request.form["email"]
        password=request.form["password"]
        user=User(
            name=name,
            email=email,
            password=password
        )
        user.save()
        data={
            'id':user.id,
            'name':user.name,
            'email':user.email,
            'password':user.password
        }
        return data
    
def edit_user_function(data):
    if request.method == "POST":
        data.name=request.form['name']
        data.email=request.form['email']
        data.password=request.form['password']
        db.session.commit()

        return data
    
def delete_user_function(user):
    db.session.delete(user)
    db.session.commit()

src/routes.py
import sys
from flask import Blueprint,render_template,redirect,url_for
from controllers.user import add_user_function,edit_user_function,delete_user_function
from models.user import User

main = Blueprint('main',__name__) #routname = main

@main.route('/',methods=['GET'])
def home():
    data = User.get_all()
    return render_template('index.html',data=data)

@main.route('/adduser',methods=['GET','POST'])
def add_user():
    data = add_user_function()
    print(data,file=sys.stderr)
    return render_template('adduser.html', data=data)


@main.route('/edituser/<int:id>',methods=['GET','POST'])
def edit_user(id):
    user = User.get_by_id(id)
    data = edit_user_function(user)
    return render_template('edituser.html',user=user,data=data)

@main.route('/deleteuser/<int:id>',methods=['POST'])
def delete_user(id):
    user = User.get_by_id(id)
    delete_user_function(user)
    return redirect(url_for('main.home'))

src/templates/adduser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask Aplication</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-8 col-xl-6">
                <nav>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="/">Home</a>
                        </li>
                    </ol>
                </nav>
                <div class="card rounded-3">
                    <div class="card-body p-4 p-md-5">
                        <h2 class="mb-4 pb-2 pb-mb--0 mb-md-5 px-md-2 text-center">Add User</h2>
                        <form method="post" action="/edituser">
                            <div class="form-group">
                                <input type="text" name="name" id="name" class="form-control" placeholder="Name" /><br>
                            </div>
                            <div class="form-group">
                                <input type="text" name="email" id="email" class="form-control" placeholder="Email" /><br>
                            </div>
                            <div class="form-group">
                                <input type="password" name="password" id="password" class="form-control" placeholder="Password" /><br>
                            </div>
                            <br>
                            <br>
                            <button type="submit" class="btn btn-success text-center">Add</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

src/templates/edituser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask Aplication</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-8 col-xl-6">
                <nav>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="/">Home</a>
                        </li>
                    </ol>
                </nav>
                <div class="card rounded-3">
                    <div class="card-body p-4 p-md-5">
                        <h2 class="mb-4 pb-2 pb-mb--0 mb-md-5 px-md-2 text-center">Edit User</h2>
                        <form method="post" action="/edituser/{{user.id}}">
                            <div class="form-group">
                                <input type="text" name="name" id="name" class="form-control" placeholder="{{user.name}}" value="{{user.name}}" /><br>
                            </div>
                            <div class="form-group">
                                <input type="text" name="email" id="email" class="form-control" placeholder="{{user.email}}" value="{{user.email}}" /><br>
                            </div>
                            <div class="form-group">
                                <input type="password" name="password" id="password" class="form-control" placeholder="{{user.password}}" value="{{user.password}}" /><br>
                            </div>
                            <br>
                            <br>
                            <button type="submit" class="btn btn-success text-center">Update</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

src/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask Aplication</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <script>
        function confirmDelete(user_id){
            var confirmation = confirm("Are you sure you want to delete this user?");
            if(confirmation){
                var form = document.createElement('form');
                form.method = 'POST';
                form.action="/deleteuser/"+user_id;
                document.body.appendChild(form);
                form.submit();
            }
        }
    </script>
</head>
<body>
    <div class="my-5 text-center">
        <a class="btn btn-primary" href="{{url_for('main.add_user')}}" role="button">Add User</a>

        <br>
        <div class="w-70 d-flex p-5">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                    {% for item in data %}
                    <tr>
                        <th scope="row">{{item.id}}</th>
                        <td>{{item.name}}</td>
                        <td>{{item.email}}</td>
                        <td>
                            <a class="btn btn-success" href="{{url_for('main.edit_user',id=item.id)}}" role="button">Edit</a>
                            <button class="btn btn-danger" onclick="confirmDelete('{{item.id}}')">Delete</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
        </div>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>